server:
  port: 8089
  contextPath: /

logging:
  level:
    learning: trace

spring:
  data:
      elasticsearch:
        cluster-name: bigdata
        #默认为elasticsearch
        cluster-nodes: hadoop01:9300,hadoop02:9300,hadoop03:9300
        client.transport.sniff: false
        #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
#        properties:
#            path:
#                logs: ./elasticsearch/log #elasticsearch日志存储目录
#                data: ./elasticsearch/data #elasticsearch数据存储目录
  #数据源配置
  datasource:
    url: jdbc:mysql://47.94.196.195:3306/bigdata?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/superclass?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dl575153
#    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
  #MVC配置
  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: classpath*:/static/*
  #tomcat配置
  tomcat:
    uri-encoding: UTF-8
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb


mybatis-plus:
  mapper-locations: classpath*:com/wxstc/bigdata/mapper/*.xml
  typeAliasesPackage: com.wxstc.dl.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用